### ISSUE TITLE
[Installation] sudo pip3 install cassandra-medusa[AZURE] fails

### ISSUE THREAD

**Issue by rjshrjndrn** [thelastpickle/cassandra-medusa#282] opened 2021-02-08 08:05 UTC
Hi, 
Thanks for this awesome application. 
I was trying to install medusa, in ubuntu 16.04 using pip3 and got below error.
I saw in another thread asking for install Medusa from master branch, But I was not sure, how it'll affect the `[AZURE]` part.
So if I install using `pip install git+https://github.com/thelastpickle/cassandra-medusa.git` will the azure integration work ?
Or do I have to do any other manual steps?

```
Collecting paramiko (from parallel-ssh==1.9.1->cassandra-medusa[AZURE])
  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 3.3MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in /usr/lib/python3/dist-packages (from retrying>=1.3.3->cassandra-medusa[AZURE])
Collecting futures>=2.2.0; python_version < "3.2" (from grpcio>=1.29.0->cassandra-medusa[AZURE])
  Downloading https://files.pythonhosted.org/packages/47/04/5fc6c74ad114032cd2c544c575bffc17582295e9cd6a851d6026ab4b2c00/futures-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2dkvptx9/futures/
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-234) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-234

**Comment by adejanovski** [comment] 2021-02-08 08:18
First thing: you'll probably need to install it using `sudo` as the installation process will create the `medusa` binary under `/usr/local/bin` and that will fail unless you `sudo` it.

If you want to install from `master`, you'll need to add the Azure requirements, by running `sudo pip install -r requirements-azure.txt` (this file can be found [here](https://github.com/thelastpickle/cassandra-medusa/blob/master/requirements-azure.txt)).

**Comment by rjshrjndrn** [comment] 2021-02-08 14:11
Hi @adejanovski I installed using `sudo pip3 install cassandra-medusa[AZURE]`

**Comment by rjshrjndrn** [comment] 2021-02-10 06:05
@adejanovski Any help highly appreciated. I tried the debian package. The installation went smooth. But I think the package is outdated, as it's not supporting the `azure` storage backend

```
[2021-02-10 06:02:33,056] INFO: Monitoring provider is noop
[2021-02-10 06:02:33,056] ERROR: This error happened during the backup: Unsupported storage provider
Traceback (most recent call last):
  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/backup_node.py", line 162, in main
    storage = Storage(config=config.storage)
  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/storage/__init__.py", line 95, in _connect_storage
    raise NotImplementedError("Unsupported storage provider")
NotImplementedError: Unsupported storage provider
```
/etc/medusa/medusa.ini
```
[storage]
storage_provider = "azure_blobs"
bucket_name = cassandra-backup-medusa
key_file = /etc/medusa/azure-medusa-credentials
```
/etc/medusa/azure-medusa-credentials
```
{
    "storage_account": "cassandra-backup",
    "key": "XXXXXXXXXXXXXXXXXXXXXXXX=="
}
```
```

**Comment by adejanovski** [comment] 2021-02-10 07:07
Re-reading the whole thread, I notice that you're using Ubuntu 16.04. We stopped building debian packages for trusty as it ships with python 3.5 which we don't support anymore as it reached EOL.
If you have Python 3.6 installed though, you can achieve what you're after by running the following commands:

```
sudo pip3 install git+https://github.com/thelastpickle/cassandra-medusa.git
sudo pip3 install azure-cli
```

Let me know how this works.

**Comment by rjshrjndrn** [comment] 2021-02-10 07:12
@adejanovski I'm not an expert in python. I can't obviously upgrade python in the prod server. Is there any way to install this in a virtual env, like `venv` or something like that. But the issue is you can't put medusa binary in `/usr/local/bin`. It's okay with me to activate the `venv` and use that for medusa.

One more question, does the apt bundle use python from the system, or contain its own runtime?

**Comment by adejanovski** [comment] 2021-02-10 07:32
To be more specific, we won't be building xenial/trusty packages starting with 0.9. 
You should have 0.8.1 packages that ship with Azure storage support, but there are fixes in `master` that would be good for you to have in order to have proper support for multi part uploads.

The debian packages do ship with a virtualenv, but we didn't manage to properly build xenial packages with Python 3.6.
If you feel like that's something you can pull off, it would be greatly appreciated.
Stretch/Xenial builds were removed [in this commit](https://github.com/thelastpickle/cassandra-medusa/commit/73ebe5ae5143012f8b2f998b8d9712fb8ba2af17#diff-a321c7875a73578c24c18a7634c71ff287682ea9c6c66a77e88a977c0ff02419) if you want to take a look.

**Comment by rjshrjndrn** [comment] 2021-02-10 08:14
Thank you @adejanovski  for your prompt responses. I'm looking into building medusa with all libraries included, which means a static build, which any Linux can take and execute. If I can pull that off, I'll contribute back. I am referring to this project https://github.com/indygreg/PyOxidizer
Did anybody try such a thing before?

**Comment by adejanovski** [comment] 2021-02-10 08:29
> Did anybody try such a thing before?
Not that I know of.

I took a quick look at the project you're mentioning and it looks like it produces a single executable, compiled for a specific platform. Medusa uses two different scripts/binaries which are `medusa` and `medusa-wrapper`, which could be tricky to reproduce with this new type of packaging.
If you can pull this off, it could be very interesting but could be challenging.
Maybe it would be better spending time trying to build xenial packages with py3.6 instead of py3.5? But it's just my 2c and it's up to you to decide which path you want to explore.

**Comment by rjshrjndrn** [comment] 2021-02-10 08:36
@adejanovski I thought it sounds better to have a statically compiled executable, which can run anywhere like a rust or golang. But as you told me, time is of the essence. I'll try the compiled app approach when I'm free. But for now, I'll try to update the xenial script with 3.6. Thanks for the heads-up.

**Comment by rzvoncek** [comment] 2023-09-20 12:06
Hello, we've just release v0.16.1 with revmaped storage, and as a part of that, the azure-specific requirements went away. This makes this issue obsolete, so I'll close it. But please reach out if you're still having issues.

**Closed by rzvoncek** 2023-09-20 12:06 UTC
Labels: new, to-groom
