### ISSUE TITLE
list-backups on IBMCLOUD S3 failed

### ISSUE THREAD

**Issue by NLatarche** [thelastpickle/cassandra-medusa#551] opened 2022-12-30 16:12 UTC
The list-backups ,  verify and status failed with the some error  : 
LibcloudError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faf2d9181d0> 'Unexpected status code: 404'>

(python3-virtualenv-cassandra) $ medusa -v list-backups
[2022-12-30 15:57:54,601] DEBUG: Loading configuration from /etc/medusa/medusa.ini
[2022-12-30 15:57:54,604] DEBUG: Loading storage_provider: s3_compatible
[2022-12-30 15:57:54,605] DEBUG: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
[2022-12-30 15:57:54,607] DEBUG: Changing event name from before-call.apigateway to before-call.api-gateway
[2022-12-30 15:57:54,608] DEBUG: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
[2022-12-30 15:57:54,610] DEBUG: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
[2022-12-30 15:57:54,610] DEBUG: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
[2022-12-30 15:57:54,610] DEBUG: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
[2022-12-30 15:57:54,611] DEBUG: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
[2022-12-30 15:57:54,614] DEBUG: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
[2022-12-30 15:57:54,615] DEBUG: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
[2022-12-30 15:57:54,615] DEBUG: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
[2022-12-30 15:57:54,615] DEBUG: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
[2022-12-30 15:57:54,615] DEBUG: Setting config variable for region to 'eu-fr2'
[2022-12-30 15:57:54,615] DEBUG: Setting AWS credentials file to /etc/medusa/medusa-ibm-credentials
[2022-12-30 15:57:54,616] DEBUG: Setting config variable for credentials_file to '/etc/medusa/medusa-ibm-credentials'
[2022-12-30 15:57:54,618] DEBUG: IMDS ENDPOINT: http://169.254.169.254/
[2022-12-30 15:57:54,620] DEBUG: Looking for credentials via: env
[2022-12-30 15:57:54,620] DEBUG: Looking for credentials via: assume-role
[2022-12-30 15:57:54,621] DEBUG: Looking for credentials via: assume-role-with-web-identity
[2022-12-30 15:57:54,621] DEBUG: Looking for credentials via: sso
[2022-12-30 15:57:54,621] DEBUG: Looking for credentials via: shared-credentials-file
[2022-12-30 15:57:54,621] INFO: Found credentials in shared credentials file: /etc/medusa/medusa-ibm-credentials
[2022-12-30 15:57:55,483] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 15:58:15,517] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 15:58:55,660] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 16:00:15,753] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 16:02:15,821] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 16:04:15,969] DEBUG: [Storage] Listing objects in index/backup_index
[2022-12-30 16:06:16,623] DEBUG: [Storage] Listing objects in index/backup_index
Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/bin/medusa", line 8, in <module>
    sys.exit(cli())
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/medusacli.py", line 185, in list_backups
    medusa.listing.list_backups(medusaconfig, show_all)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/listing.py", line 41, in list_backups
    cluster_backups = get_backups(config, show_all)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/listing.py", line 29, in get_backups
    key=lambda b: b.started
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 354, in list_cluster_backups
    key=lambda b: (b.name, b.started)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 188, in list_node_backups
    backup_index_blobs = self.list_backup_index_blobs()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 279, in list_backup_index_blobs
    return self.storage_driver.list_objects(path)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/abstract_storage.py", line 55, in list_objects
    objects = self.driver.list_container_objects(self.bucket, ex_prefix=str(path))
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/storage/base.py", line 339, in list_container_objects
    ex_prefix=ex_prefix))
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 341, in iterate_container_objects
    (response.status), driver=self)
libcloud.common.types.LibcloudError: <LibcloudError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faf2d9181d0> 'Unexpected status code: 404'>

it seems the error is located in   self.connection.request  line 336 in ..../libcloud/storage/drivers/s3.py that could not get the response

 330         container_path = self._get_container_path(container)
 331
 332         while not exhausted:
 333             if last_key:
 334                 params['marker'] = last_key
 335
 336             response = self.connection.request(container_path,
 337                                                params=params)
 338
 339             if response.status != httplib.OK:
 340                 raise LibcloudError('Unexpected status code: %s' %
 341                                     (response.status), driver=self)

any idea ? Thank you

**Comment by adejanovski** [comment] 2023-01-09 09:43
This is a duplicate of #550 

The cause for both issues is most likely the same: the bucket cannot be found using the provided settings.

**Closed by adejanovski** 2023-01-09 09:43 UTC
Labels: new
