### ISSUE TITLE
Infinite Loop during the restoration

### ISSUE THREAD

**Issue by TryToWork** [thelastpickle/cassandra-medusa#174] opened 2020-07-16 07:56 UTC
Hello,

In the last release 0.7, the correction made requires the prior installation of the nc tool, but once the latter is installed we are again in an infinite loop when you try to restore a cluster (when Medusa will test if the seeds are UPs) ...

Cordially.

**Comment by arodrime** [comment] 2020-07-28 11:09
Hello @TryToWork, thanks for sending another feedback our way.

Could it be related to this issue #178 and fixed by this PR #179?

If not, could you share the logs you have on the server running the restore, but also the logs from the nodes (in `/tmp/medusa_<workfolder>/stderr` - or `stdout` off the top of my head)?

Thanks!

**Comment by TryToWork** [comment] 2020-07-28 12:47
Indeed obviously it is the same bug, I will test the new version when it is available.

**Comment by arodrime** [comment] 2020-07-28 13:53
Closing then as a duplicate of issue #178. I'm testing PR #179 right now. I invite you to follow up there if needed.

**Closed by arodrime** 2020-07-28 13:53 UTC
Labels: bug, new

**Comment by arodrime** [comment] 2020-07-31 14:40
@TryToWork 0.7.1 release is out and should hopefully fix your issue.
