### ISSUE TITLE
Try to restore a table/keyspace fail in some cases

### ISSUE THREAD

**Issue by DBA-begin** [thelastpickle/cassandra-medusa#115] opened 2020-04-15 14:05 UTC
Hello,

I try to restore only one table or one keyspace with a full backup.

In some scenarios it works without problems but in others this fails.

Success : 
- Restore a table after do a TRUNCATE on her 👍 
- Restore a keyspace after do a TRUNCATE on somes tables and add data on other, it's work  and restore the keyspace at the moment of the backup 👍 

Fail :  (with no error message while restore)
- Restore a table after do a drop table on her 👎 
- Restore a keyspace after do a drop keyspace on him 👎 
- Restore a keyspace after do a drop keyspace and recreate empty without or with tables (empty) 👎 
- Restore a keyspace only or a table only on other cluster (empty) 👎 

But maybe it's not possible? 

Bests Regards.

**Comment by adejanovski** [comment] 2020-06-05 15:25
@DBA-begin, thanks for reporting these different scenarios and their outcomes.
We'll process these shortly and update the issue.

**Comment by rzvoncek** [comment] 2020-06-15 14:40
Hello @DBA-begin,

I've done some experiments with the cases that didn't work for you. I've used [this branch](https://github.com/thelastpickle/cassandra-medusa/compare/tests-for-115?expand=1) to add scenarios that cover your cases.

Sadly, I was not able to reproduce the problems you had. Let me explain why.

When doing a restore, Medusa works in two modes:
* In-place restores are the cases when the restore happens on the same node it did the backup.
* Out-of-place restores are the cases when the restore happens on a different node than the one that did the backup.

One of the differences among these two is that out-of-place case does not take `system.local` and `system.peers` from the backup. The main reason for this is to keep the restore target node belong to whatever cluster it was in (instead of becoming part of the backed up cluster).

In both of the cases, however, Medusa takes the `system.schema_*` tables and makes the restore node load them. This basically means that whatever the schema was before the restore, it's going to be thrown away and the schema from the backup will become live.

This means the errors you experienced must be caused by something else. To keep things clear, I'll close this issue, but please feel free to open new ones to look more into particular cases. The more information you provide with in the issues, the more likely we'll be able to help.

**Closed by rzvoncek** 2020-06-15 14:40 UTC
Labels: bug, critical

**Comment by rzvoncek** [comment] 2020-06-15 15:29
I understood a bit later that all of the above applies only if sstableloader is not used.

When using sstableloader, things are a bit different. 
* When doing a `restore_cluster`, Medusa [has an explicit code](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/restore_cluster.py#L419) to (re)create the schema.
* When doing a `restore_node`, there is no such code and Medusa simply invokes the sstableloader expecting the schema is already there.

So restoring a single node with sstableloader will not work if the schema in the cluster doesn't contain that table.

**Comment by DBA-begin** [comment] 2020-06-16 12:42
Thank you for your answer but to be clear (because I think there is a misunderstanding), if I execute the following command:

Case 1:

All the nodes:
medusa backup --backup-name="backupName" --mode=full 

One node :
cqlsh> drop keyspace cycling; 

I restore on the same cluster
medusa -v restore-cluster --backup-name="backupName" --table cycling.birthday_list --seed-target server1 

Normaly in my cluster after restore i have only one table in keyspace cycling or no?

Case 2:

All the nodes:
medusa backup --backup-name="backupName" --mode=full 

I restore on an another cluster (without datas)
medusa -v restore-cluster --backup-name="backupName" --host-list /etc/medusa/restore_mapping.txt  --table cycling.birthday_list --bypass-checks 

Normaly in my new cluster after restore i have only one table in keyspace cycling or no?

Case 3:

All the nodes:
medusa backup --backup-name="backupName" --mode=full 

I restore on an another cluster (without datas)
medusa -v restore-cluster --backup-name="backupName" --host-list /etc/medusa/restore_mapping.txt  --keyspace cycling --bypass-checks 

Normaly in my new cluster after restore i have only one keyspace cycling or no?


Case 4:

All the nodes:
medusa backup --backup-name="backupName" --mode=full 

One node :
cqlsh> drop table cycling.birthday_list; 

I restore on the same cluster
medusa -v restore-cluster --backup-name="backupName" --table cycling.birthday_list --seed-target server1 

Normaly in my cluster after restore i have my data in cycling.birthday_list or no?
